### ISSUE TITLE
ERROR Failed to download on some posts

### ISSUE THREAD

**Issue by DisasterInbound** [AlexCSDev/PatreonDownloader#139]
I get the following error on some media files when downloading:

`2022-08-26 14:42:30.3401 ERROR Failed to download https://c10.patreonusercontent.com/4/patreon-media/p/post/63692522/710deacb70e940d999bf2f6032e1e2f0/eyJhIjoxLCJwIjoxfQ%3D%3D/1.png?token-time=1661644800&token-hash=xxxxxxxxxxxxxxxxxxxxxxxxxx: Error while downloading https://c10.patreonusercontent.com/4/patreon-media/p/post/63692522/710deacb70e940d999bf2f6032e1e2f0/eyJhIjoxLCJwIjoxfQ%3D%3D/1.png?token-time=1661644800&token-hash=xxxxxxxxxxxxxxxxxxxxxxxxxx: [63692522] Unable to retrieve file id for https://c10.patreonusercontent.com/4/patreon-media/p/post/63692522/710deacb70e940d999bf2f6032e1e2f0/eyJhIjoxLCJwIjoxfQ%3D%3D/1.png?token-time=1661644800&token-hash=xxxxxxxxxxxxxxxxxxxxxxxxxx, contact developer!`

I redacted the token-hash because I'm not sure if this is better to keep private but the 3 token-hash are the same.
26 out of 311 media files failed to download with the same message

**Comment by Neph81** [comment]
I find this happens if the file names are the same on the server.  In this example, I'm guessing that each file is 1.png and the downloader had issues because 1.png has already been saved for that gallery.  The fallback method for naming files doesn't work, so maybe we need an additional option for force download files even if they exist with a -1 or something in the file name.

**Comment by AlexCSDev** [comment]
This is just an issue with the regex expression used to match the url, will be fixed in the future version.

**Comment by AlexCSDev** [comment]
Should be fixed in 0.10.6.0
