### ISSUE TITLE
Mega plugin ignores download path, saves files to root of C: drive

### ISSUE THREAD

**Issue by fake-name** [AlexCSDev/PatreonDownloader#159]
Effectively the title.

```
PatreonDownloader.App.exe --version
Patreon Downloader 23.0.0.0
```

Host is W10 22H2.

I'm running this in a VM where I have very little free space in the root drive (<5 GB): 

```
PatreonDownloader.App.exe --url https://www.patreon.com/<artist>/posts --descriptions --embeds --campaign-images --json --log-level Trace --download-directory O:\pattest\<artist> || exit /b
```

The Mega downloader seems to be using a creating/using cache directory named `C:\V1hgz_<Mega Folder Name>` where it's either saving content, or saving cache things, and it pretty quickly runs the host out of disk space and starts failing in interesting ways.  

Off topic: When mega issues a `509 Bandwidth exceeded` error, the downloader just winds up doing 10 retries for every mega item, which is kind of annoying. It'd be neat if it were smart enough to give up on mega files for a while when it hits a 509, but it should at least stop doing pointless retries.

**Comment by fake-name** [comment]
Ok, I think something is eating the download parameter that's getting passed to the plugin, and everything else is a result of that issue. 

Skimming the code, I don't see how, though.

**Comment by AlexCSDev** [comment]
While I appreciate all bug reports, I ask everyone to refrain from trying to teach me how things are supposed to be done without completely understanding how the application is designed and supposed to work. Thank you.

In this case it's clearly not supposed to download into the root of C: drive. Make sure you are running latest version, I cannot replicate this on release 23.

**Comment by AlexCSDev** [comment]
Ok, since it's pretty late in the night I have actually missed the fact that you already running latest version, let me test a few things and I'll get back to you.

**Comment by fake-name** [comment]
> While I appreciate all bug reports, I ask everyone to refrain from trying to teach me how things are supposed to be done without completely understanding how the application is designed and supposed to work. Thank you.

Sorry, I get snarky when I'm irritated.

I wrote a bunch of that, and then dug about a bunch and realized there wasn't anything that would try to create a temp directory, and it was probably a path truncation/drive weirdness issue. I should have removed a bunch of comments at that point.

**Comment by AlexCSDev** [comment]
Unfortunately I can't replicate it on my side. Unless other people report this issue or you'll be able to debug it yourself all I can guess is that you either have leftover files from other builds or some application files have managed to cache somehow.

SHA-256 hash for `plugins\UniversalDownloaderPlatform.MegaDownloader.dll` is supposed to be: 727B34ACE5152F668878505F502F8E86BD73C13FF06BB2C9A51E5E006A7963E9

**Comment by fake-name** [comment]
> Unfortunately I can't replicate it on my side no matter what I do. Unless other people report this issue or you'll be able to debug it yourself all I can guess is that you either have leftover files from older builds or some application files have managed to cache somehow.

I'm not actually running my own build currently, just a folder where I unzipped the latest release. 

I'll stick print statements about and poke it when I can.

**Comment by AlexCSDev** [comment]
Sounds good, because this code is being used across 3 different applications and I don't see any issues with it on my side in any of those application.

**Comment by emerladCoder** [comment]
I'm having the same/similar issue. Mega Plugin is downloading to the Root of the drive the application is running from (I have tested that by moving the application folder to different drives and it always downloads in root of the drive the application is running from, even if the download folder is in another drive)

All other files download to correct location (post, media, attachments, description, json, embed.txt, cover, avatar, etc.) Its only the plugin files and folders that are somehow losing the download directory.

I am also running the version 23. This issue does not occur in version 22 (but version 22 has the attachment naming issue bug that's more annoying in my opinion).

In the log the download path just starts with a \

`[UniversalDownloaderPlatform.MegaDownloader.MegaDownloader] [MEGA] Downloading <filename> to \<id>_<filename>`

Instead of like in version 22 where it has the download directory

`[UniversalDownloaderPlatform.MegaDownloader.MegaDownloader] [MEGA] Downloading <filename> to <download-directory>\<id>_<filename>`

**Comment by AlexCSDev** [comment]
@emerladCoder  Thank you for your detailed look into the problem. This is actually an issue which slipped through while I was doing refactoring. Since `DownloadPath` is supposed to represent a directory relative to the download path it should be completely empty when `--use-sub-directories` is not used. Will fix that asap.

**Comment by AlexCSDev** [comment]
Released new version addressing this issue: https://github.com/AlexCSDev/PatreonDownloader/releases/tag/release_24
