### ISSUE TITLE
Project build issue on submodules

### ISSUE THREAD

**Issue by nothankyouthisisdumb** [AlexCSDev/PatreonDownloader#162]
![image](https://user-images.githubusercontent.com/123428556/214194349-cdd5e712-d911-4c5f-b8ed-8ad251024204.png)
![image](https://user-images.githubusercontent.com/123428556/214194377-77c5df9c-ad72-4ee7-b6f8-f26878278a7f.png)

never worked with code/software before, any further guide on compiling?

**Comment by AlexCSDev** [comment]
Refer to docs/building.md for building instructions. If I were to guess you probably have not cloned submodules.

**Comment by nothankyouthisisdumb** [comment]
I definitely did something wrong, I re-cloned the submodules and got further! 
![image](https://user-images.githubusercontent.com/123428556/214195656-d4f89e4c-5940-4d2f-b918-a2254b1d07eb.png)
![image](https://user-images.githubusercontent.com/123428556/214195755-df5a6976-f507-4035-a7f3-87888db3099e.png)
![image](https://user-images.githubusercontent.com/123428556/214195781-573bc954-0fcd-49da-b1f2-80e37d8b1079.png)

**Comment by emerladCoder** [comment]
This is due to path in the solution file and csproj file. If you update the paths you should be able to compile without issue.

PatreonDownloader.sln
`Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "UniversalDownloaderPlatform.PuppeteerEngine", "..\XMADownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.PuppeteerEngine\UniversalDownloaderPlatform.PuppeteerEngine.csproj", "{2EF4E7BA-9E1C-43D7-B483-AD5D90033631}"`
Correct to
`Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "UniversalDownloaderPlatform.PuppeteerEngine", "submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.PuppeteerEngine\UniversalDownloaderPlatform.PuppeteerEngine.csproj", "{2EF4E7BA-9E1C-43D7-B483-AD5D90033631}"`

PatreonDownloader.Implementation\PatreonDownloader.Implementation.csproj
` <ProjectReference Include="..\..\XMADownloader\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.PuppeteerEngine\UniversalDownloaderPlatform.PuppeteerEngine.csproj" />`
Correct to
 `<ProjectReference Include="..\submodules\UniversalDownloaderPlatform\UniversalDownloaderPlatform.PuppeteerEngine\UniversalDownloaderPlatform.PuppeteerEngine.csproj" />`

**Comment by AlexCSDev** [comment]
Well this is weird, dunno how visual studio managed to reference project from the wrong path. Fixed.
