### ISSUE TITLE
Some creators do not have creator name

### ISSUE THREAD

**Issue by ITJesse** [AlexCSDev/PatreonDownloader#22]
For example:
(NSFW) https://www.patreon.com/m/605785/posts

I tried to use `m/605785` as the creator name.

Well, it started to work but stalled at the downloading progress.
The download folder it created was `download\m\605785`.

I am not sure whether this is correct or not.

Thanks.

**Comment by Liz-chan** [comment]
I actually have the same issue too atm, and using the ID doesn't work.

**Comment by AlexCSDev** [comment]
Right now PatreonDownloader assumes that every creator has a creator name. The best way to solve this is probably to change the way creator gets passed to application so it takes full url instead of creator's name. I'll try to find some free time this weekend to make it possible, shouldn't be very hard to implement.

@Liz-chan can you give the url for the creator you're having trouble with? I have no idea how many different url patterns patreon uses so I need to have as many examples as possible.

**Comment by Liz-chan** [comment]
@AlexCSDev Yeah, here you go: https://www.patreon.com/user?u=32547544

**Comment by AlexCSDev** [comment]
@Liz-chan Thanks.

**Comment by oliviaputtel** [comment]
Here is more
https://www.patreon.com/user/posts?u=9011118

**Comment by oliviaputtel** [comment]
@AlexCSDev We need `creator` option to create the download directory. So maybe just add the `url` option

**Comment by AlexCSDev** [comment]
Solved in 0.9.3
