### ISSUE TITLE
"Original"-Image is not downloaded 

### ISSUE THREAD

**Issue by duracell** [AlexCSDev/PatreonDownloader#47]
Hey, thanks for this program, I tested it and it works really nice, the only thing which is weird is that it doesn't download the full size images. So if there is an post with an image which is bigger if I click on it, it just saves 2 times the small thumbnail.
In the json there is the correct url for the bigger one saved as "original", so it seems like a bug for me that this isn't downloaded.

**Comment by AlexCSDev** [comment]
Please send me a json dump with brief explanation which post you encounter issues on, url of the file you expect to be downloaded and url of the file being downloaded instead. Email: alexcsdev@protonmail.com

**Comment by AlexCSDev** [comment]
Sorry, I've been quite busy lately. I've got your email and will check what might be wrong within next few days.

**Comment by duracell** [comment]
Should this be fixed in the current release? I don't have any patreon pages with pictures available, but would love to know if this got fixed :)

**Comment by AlexCSDev** [comment]
I haven't looked into this specific case on latest version, but neither I nor anyone else observed any issues with file downloading so far.

**Comment by Site3op** [comment]
There isnt any problem with file downloading but it does not download source files. If you download the files how they would typically be downloaded they are double the size and a bigger image scale than what is scrapped from this downloader.

**Comment by AlexCSDev** [comment]
I think this might be fixed with the latest build? Needs to be tested.

**Comment by AlexCSDev** [comment]
Ok, I've done some testing across several different patreon pages. Here are the results:

File downloaded by PatreonDownloader:
![image](https://user-images.githubusercontent.com/942091/215923802-516afcd8-a08a-4883-9b8c-8596f2435342.png)

File downloaded via browser/from the url marked as "original":
![image](https://user-images.githubusercontent.com/942091/215923876-be64f242-a220-4065-b215-4ba76b96dda0.png)

Notice that the "original" file lacks `Software` field. **This file has been processed** after being uploaded to patreon while the one downloaded by PatreonDownloader still got EXIF data intact. 

More so, I have compared the file downloaded by PatreonDownloader to the file contained in the monthly archive uploaded by the artist to google drive. **The file hash is absolutely identical** while the file downloaded via the browser is bigger in file size and has different hash.

Henceworth the true original file is the one downloaded by the PatreonDownloader, not the one you get via the browser. Given that information this issue is now closed as invalid.
